/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Combo_box;
import Control.Control_cliente;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDRES
 */

public class Interfaz_cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_cliente
     */
    Combo_box cbx = new Combo_box();
    public Interfaz_cliente() {
        initComponents();
        limpiar();
        
        jTextField_cod_ciudad.setEnabled(false);
        jTextField_fechanac.setDateFormatString("dd/MM/yyyy");
        Object[] ciu = cbx.combox("ciudades","nombre_ciudad");
        jComboBox_ciudad.removeAllItems();
        for(int i=0;i<ciu.length;i++){
        jComboBox_ciudad.addItem(ciu[i]);
        jTextField_cod_ciudad.setVisible(false);
        this.setTitle("Registro de clientes");
        URL pathIcon = this.getClass().getClassLoader().getResource("Imagenes/LLANTA.PNG");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(pathIcon);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_documento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_apellidos = new javax.swing.JTextField();
        jComboBox_tipo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_ciudad = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_sexo = new javax.swing.JComboBox();
        jTextField_cod_ciudad = new javax.swing.JTextField();
        jTextField_fechanac = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setText("Documento");

        jTextField_documento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_documentoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setText("Nombres");

        jTextField_nombres.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombresKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos");

        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setText("Dirección");

        jTextField_direccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel5.setText("Correo");

        jTextField_correo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel6.setText("Fecha nac.");

        jTextField_apellidos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField_apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_apellidosKeyTyped(evt);
            }
        });

        jComboBox_tipo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CC", "TI", "RC", "PASAPORTE", "CE", "RUT", "NIT" }));

        jLabel7.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel7.setText("Tipo documento");

        jLabel8.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel8.setText("Ciudad");

        jComboBox_ciudad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox_ciudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ciudadActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardarpeq.png"))); // NOI18N
        jButton1.setText("Registar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel9.setText("Sexo");

        jComboBox_sexo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox_sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        jTextField_cod_ciudad.setForeground(new java.awt.Color(0, 153, 204));
        jTextField_cod_ciudad.setBorder(null);

        jTextField_fechanac.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addComponent(jComboBox_sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jTextField_direccion)
                            .addComponent(jTextField_fechanac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTextField_documento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(22, 22, 22)
                        .addComponent(jComboBox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_correo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jComboBox_ciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_cod_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)
                        .addComponent(jTextField_cod_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_fechanac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void limpiar()
    {
       jTextField_documento.setText("");
       jTextField_nombres.setText("");
       jTextField_apellidos.setText("");
       jTextField_direccion.setText("");
       jTextField_correo.setText("");
       jTextField_fechanac.setCalendar(null);
        
    }
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String doc,nom,ape,dir,ciu,tipo,correo,sex; 
        
        doc = jTextField_documento.getText();
        tipo= jComboBox_tipo.getSelectedItem().toString();
        nom = jTextField_nombres.getText();
        ape = jTextField_apellidos.getText();
        dir = jTextField_direccion.getText();        
        ciu = jTextField_cod_ciudad.getText();
        sex = jComboBox_sexo.getSelectedItem().toString();
        // Patrón para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+"[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        // El email a validar
        String email = jTextField_correo.getText();
        Matcher mather = pattern.matcher(email);
        
        if (mather.find() == true) {
            Control_cliente contr = new Control_cliente(doc, tipo, nom, ape, dir,sex,email,Integer.parseInt(jTextField_cod_ciudad.getText()));
        if(!doc.equals("") && !tipo.equals("") && !nom.equals("") && !ape.equals("") && !dir.equals("") && !ciu.equals("") )
        {
            if(contr.registrar("clientes"))
            {
            JOptionPane.showMessageDialog(null,"El cliente se registro con exito ","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            limpiar();

            }
            else
            {
            JOptionPane.showMessageDialog(this, "Error al registrar el cliente");
            }
            }
            else
            {
              JOptionPane.showMessageDialog(this, "Hay campos obligatorios");  
            }
        } else {
                JOptionPane.showMessageDialog(null,"El email ingresado es inválido.");
        }
        
        
        
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ciudadActionPerformed
    if(jComboBox_ciudad.getSelectedItem()!=null )
     {
            
            Object[][] datos = cbx.ingresa_cod(jComboBox_ciudad.getSelectedItem().toString(), "id_ciudad", "ciudades","nombre_ciudad");
            jTextField_cod_ciudad.setText(datos[0][0].toString()); 
            
}        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ciudadActionPerformed

    private void jTextField_documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_documentoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(Character.isDigit(car)){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextField_documentoKeyTyped

    private void jTextField_nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombresKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(Character.isLetter(car)){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextField_nombresKeyTyped

    private void jTextField_apellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_apellidosKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(Character.isLetter(car)){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextField_apellidosKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox_ciudad;
    private javax.swing.JComboBox jComboBox_sexo;
    private javax.swing.JComboBox jComboBox_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField_apellidos;
    private javax.swing.JTextField jTextField_cod_ciudad;
    private javax.swing.JTextField jTextField_correo;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_documento;
    private com.toedter.calendar.JDateChooser jTextField_fechanac;
    private javax.swing.JTextField jTextField_nombres;
    // End of variables declaration//GEN-END:variables
}
