/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Exportar.Exporter;
import Control.Control_contratos;
import Control.Control_vendedor;
import Exportar.Exporter;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.time.Month;
import java.time.Year;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sun.java2d.pipe.SpanShapeRenderer;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 
 */
public class Interfaz_repventas extends javax.swing.JInternalFrame {

    /**
     * 
     */
    URL pathIcon = this.getClass().getClassLoader().getResource("Imagenes/LLANTA.PNG");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(pathIcon);
        
    private Object[][] tabla;
    Control_contratos con = new Control_contratos();
    public Interfaz_repventas() {
        initComponents();
        mostrar_tabla();
        jDateChooser.setDateFormatString("dd/MM/yyyy");
        DecimalFormat formatea = new DecimalFormat("###,###.##");
        Totalizar();
        this.setTitle("Reporte de ventas");
        
        
        
    }
    
    
    public String convertirFechaString(Date date){
        Format formatter = new SimpleDateFormat("dd/MM/yyyy");
	return formatter.format(date);
    }
    
    private void Totalizar(){
        DecimalFormat formatea = new DecimalFormat("###,###.##");
        int t=0;
        int p=0;
        if (jTable1.getRowCount()>0){
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                p=Integer.parseInt(jTable1.getValueAt(i, 4).toString());
                t += p;
                
            }
            jLabelTotal.setText("$ " +formatea.format(t)+" COP");
   
            
        }else{
            //Sin condi
        }
    
    }
   public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
        //cargaTicket();
    }
   public void mostrar_tabla(){
       
        Control_contratos contr;       
        contr = new Control_contratos();
        String[] columnas = {"Factura Número","Fecha","Cliente","Vendedor","Valor"};
        tabla = contr.datos_contrato();
        DefaultTableModel datos = new DefaultTableModel(tabla,columnas);
        jTable1.setModel(datos);
        TableRowSorter<DefaultTableModel> elQueOrdena = new TableRowSorter<DefaultTableModel>(datos);
        jTable1.setRowSorter(elQueOrdena);
        jLabelTotal.setVisible(true);
        
    }
   public void mostrar_tablaFiltro(String fecha){
        Control_contratos contr;       
        contr = new Control_contratos();
        String[] columnas = {"Factura Número","Fecha","Cliente","Vendedor","Valor"};
        tabla = contr.datos_contratoFech(fecha);
        DefaultTableModel datosF = new DefaultTableModel(tabla,columnas);
        jTable1.setModel(datosF);
    }
   
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtExportar = new javax.swing.JButton();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        Btfiltrar = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabelTotal1 = new javax.swing.JLabel();
        btTodo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 760, 307));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setText("TOTAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        BtExportar.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        BtExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excelpeq.png"))); // NOI18N
        BtExportar.setText("    Exportar a Excel");
        BtExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExportarActionPerformed(evt);
            }
        });
        getContentPane().add(BtExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, 31));

        jDateChooser.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 32, 219, 37));

        Btfiltrar.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        Btfiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/filtrapeqmas.png"))); // NOI18N
        Btfiltrar.setText("     Filtrar Busqueda");
        Btfiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtfiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(Btfiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 98, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 270, 40));

        jLabelTotal1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        getContentPane().add(jLabelTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 270, 40));

        btTodo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        btTodo.setText("Mostrar todo");
        btTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 223, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtfiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtfiltrarActionPerformed
        // TODO add your handling code here:
        
        if (jDateChooser.getDate()==null) {
            
            JOptionPane.showMessageDialog(null, "Sin fecha para filtrar.");
           
        }else{
            String fecha = convertirFechaString(jDateChooser.getDate());
            mostrar_tablaFiltro(fecha);
            Object[][] datosF = con.datos_contratoFech(fecha);
            jLabelTotal.setVisible(false);
            jLabelTotal1.setVisible(true);
            jLabelTotal1.setText("$ 130.000.000 COP");
        }
            
    }//GEN-LAST:event_BtfiltrarActionPerformed

    private void BtExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExportarActionPerformed
        // TODO add your handling code here:
        
        if (this.jTable1.getRowCount()==0) {
            
            JOptionPane.showMessageDialog(null, "No hay datos en la tabla para exportar.", "Concesinario", JOptionPane.INFORMATION_MESSAGE);

        }
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar archivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION) {
           List<JTable> tb = new ArrayList<JTable>();
           List<String>nom=new ArrayList<String>();
           tb.add(jTable1);
           nom.add("Concesionario");
           String file = chooser.getSelectedFile().toString().concat(".xls");
            try {
                Exportar.Exporter e = new Exporter(new File(file), tb, nom);
                if (e.export()) {
                    JOptionPane.showMessageDialog(null, "Los datos fueron exportados a Excel.","Concesionario",JOptionPane.INFORMATION_MESSAGE);
                    
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido algo "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_BtExportarActionPerformed

    private void btTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodoActionPerformed
        // TODO add your handling code here:
        mostrar_tabla();
        jLabelTotal1.setVisible(false);
        jLabelTotal.setVisible(true);
    }//GEN-LAST:event_btTodoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtExportar;
    private javax.swing.JButton Btfiltrar;
    private javax.swing.JButton btTodo;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotal1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
