/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import Control.Combo_box;
import Control.Control_auto;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author ANDRES
 */
public class Interfaz_autos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_autos
     */
    Combo_box cb = new Combo_box();
    public Interfaz_autos() {
        initComponents();
        URL pathIcon = this.getClass().getClassLoader().getResource("Imagenes/LLANTA.PNG");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(pathIcon);
        
        jTextField_codciudad.setVisible(false);
        jTextField_tipo.setVisible(false);
        jTextField_marca.setVisible(false);
       Object[] ciu = cb.combox("ciudades","nombre_ciudad");
        jComboBox_ciudad.removeAllItems();
        for(int i=0;i<ciu.length;i++){
        jComboBox_ciudad.addItem(ciu[i]);
        this.setTitle("Registro de autos");
    }
        
        Object[] marca = cb.combox("marcas","descripcion");
        jComboBox_marca.removeAllItems();
        for(int i=0;i<marca.length;i++){
        jComboBox_marca.addItem(marca[i]);
    }
        
        Object[] tipo = cb.combox("tipo_carros","descripcion_tipo");
        jComboBox_tipo.removeAllItems();
        for(int i=0;i<tipo.length;i++){
        jComboBox_tipo.addItem(tipo[i]);
    }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_placa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_modelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_color = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_ciudad = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_marca = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_tipo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jTextField_codciudad = new javax.swing.JTextField();
        jTextField_marca = new javax.swing.JTextField();
        jTextField_tipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_motor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(new java.awt.Color(204, 204, 255));
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel1.setText("Placa");

        jTextField_placa.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setText("Modelo");

        jTextField_modelo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel3.setText("No motor");

        jTextField_color.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel4.setText("Ciudad");

        jComboBox_ciudad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox_ciudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ciudadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel5.setText("Marca");

        jComboBox_marca.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox_marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_marcaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel6.setText("Tipo carro");

        jComboBox_tipo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardarpeq.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel10.setText("Color");

        jTextField_motor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextField_modelo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .add(jTextField_placa)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel10))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextField_motor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .add(jTextField_color))))
                .add(38, 38, 38)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jComboBox_ciudad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jComboBox_marca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jLabel6)
                        .add(18, 18, 18)
                        .add(jComboBox_tipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField_marca)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField_codciudad)
                    .add(jTextField_tipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton2)
                .add(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(47, 47, 47)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField_placa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField_modelo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jTextField_motor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField_color, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox_ciudad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(jTextField_codciudad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox_marca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(jTextField_marca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField_tipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox_tipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(36, 36, 36)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void limpiar()
    {
       jTextField_placa.setText("");
       jTextField_codciudad.setText("");
       jTextField_marca.setText("");
       jTextField_tipo.setText("");
       jTextField_modelo.setText("");
       jTextField_motor.setText("");
       jTextField_color.setText("");
    }
    private void jComboBox_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ciudadActionPerformed
   if(jComboBox_ciudad.getSelectedItem()!=null )
     {
            
            Object[][] datos = cb.ingresa_cod(jComboBox_ciudad.getSelectedItem().toString(), "id_ciudad", "ciudades","nombre_ciudad");
            jTextField_codciudad.setText(datos[0][0].toString()); 
            
}             // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ciudadActionPerformed

    private void jComboBox_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_marcaActionPerformed
   if(jComboBox_marca.getSelectedItem()!=null )
     {
            
            Object[][] datos = cb.ingresa_cod(jComboBox_marca.getSelectedItem().toString(), "id_marca", "marcas","descripcion");
            jTextField_marca.setText(datos[0][0].toString()); 
            
}                 // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_marcaActionPerformed

    private void jComboBox_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipoActionPerformed
    if(jComboBox_tipo.getSelectedItem()!=null )
     {
            
            Object[][] datos = cb.ingresa_cod(jComboBox_tipo.getSelectedItem().toString(), "idtipo_carro", "tipo_carros","descripcion_tipo");
            jTextField_tipo.setText(datos[0][0].toString()); 
            
}             // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            String pla,ciu,mar,tip,mod,mot,col; 
            //int estado=1;
            pla = jTextField_placa.getText().toUpperCase();
            ciu= jTextField_codciudad.getText();
            mar = jTextField_marca.getText();
            tip = jTextField_tipo.getText();
            mod = jTextField_modelo.getText();        
            col = jTextField_color.getText().toUpperCase();
            mot = jTextField_motor.getText().toUpperCase();
            Control_auto au = new Control_auto();
            if(!pla.equals("") && !ciu.equals("") && !mar.equals("") && !mot.equals("") && !mod.equals("") && !tip.equals("") ){
                if(au.registrar_auto(pla, Integer.parseInt(ciu), Integer.parseInt(mar), Integer.parseInt(tip), Integer.parseInt(mod), col, mot)){
                    JOptionPane.showMessageDialog(null,"El carro se registro con exito ","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                    limpiar();

                }else{
                    JOptionPane.showMessageDialog(this, "Error al registrar el carro");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios");  
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox_ciudad;
    private javax.swing.JComboBox jComboBox_marca;
    private javax.swing.JComboBox jComboBox_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField_codciudad;
    private javax.swing.JTextField jTextField_color;
    private javax.swing.JTextField jTextField_marca;
    private javax.swing.JTextField jTextField_modelo;
    private javax.swing.JTextField jTextField_motor;
    private javax.swing.JTextField jTextField_placa;
    private javax.swing.JTextField jTextField_tipo;
    // End of variables declaration//GEN-END:variables
}
