/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Interfaz_concesionario;
import ConexionSQL.Conx_bd;
import Hash.Hash;
import static Hash.Hash.getSHA;
import java.awt.Color;
import java.awt.Image;
import static java.awt.SystemColor.menu;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.font.StrikeMetrics;

/**
 *
 * @author 
 */
public class Login extends javax.swing.JFrame {
    
    Conx_bd cc = new Conx_bd();
    Connection con = cc.conectado();
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
        this.getContentPane().setBackground(Color.white);
        //rsscalelabel.RSScaleLabel.setScaleLabel(candado, "src/Imagenes/logiiin.png");
        URL pathIcon = this.getClass().getClassLoader().getResource("Imagenes/LLANTA.PNG");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(pathIcon);
        this.setIconImage(img);
    }
    public void limpiar(){
        txtDoc.setText("");
       txtPass.setText("");
        
    }
    public void validarAcceso(){
        int resultado=0;
        try {
                String doc = txtDoc.getText();
                String pass = String.valueOf(txtPass.getPassword());
                String nuevaContra = null;
                try {
                    nuevaContra = Hash.toHexString(getSHA(pass));
        //        System.out.println(nuevaContra);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(Interfaz_vendedor.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println(doc);
                System.out.println(pass);
                String sql= "SELECT * FROM vendedores where No_documento='" + doc+ "' and contra='"+nuevaContra+"' ";
                
                Statement st=con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                if (rs.next()) {
                    resultado=1;
                    System.out.println(resultado);
                    if (resultado==1) {
                        Interfaz_concesionario ppal = new  Interfaz_concesionario();
                         ppal.setVisible(true);
                         dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Error en el acceso,vuelva a intentarlo");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Documento o contraseña incorrectos.");
                    limpiar();
                }    
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Error en el acceso,vuelva a intentarlo ..."+ e.getMessage());
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        BtIngresar = new javax.swing.JButton();
        candado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOG IN");
        setBackground(new java.awt.Color(51, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel1.setText("Documento");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGOSEEPDPEQ.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        txtDoc.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDoc.setMinimumSize(new java.awt.Dimension(6, 39));
        txtDoc.setPreferredSize(new java.awt.Dimension(6, 39));
        txtDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocActionPerformed(evt);
            }
        });
        txtDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocKeyTyped(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        BtIngresar.setBackground(new java.awt.Color(204, 204, 204));
        BtIngresar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        BtIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IGRESARPEQMES.png"))); // NOI18N
        BtIngresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BtIngresar.setBorderPainted(false);
        BtIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIngresarActionPerformed(evt);
            }
        });

        candado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logiiinpeq.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel3))
                                .addComponent(candado)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3))
                    .addComponent(candado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(BtIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIngresarActionPerformed
        // TODO add your handling code here:
        String doc = txtDoc.getText();
        String contraseña = String.valueOf(txtPass.getPassword());
        String nuevaContra = null;
        if (!doc.equals("")  && !contraseña.equals("") ) {
            validarAcceso();
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos.");
        }
        
    }//GEN-LAST:event_BtIngresarActionPerformed

    private void txtDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(Character.isDigit(car)){
        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtDocKeyTyped

    private void txtDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtIngresar;
    private javax.swing.JLabel candado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtDoc;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
